### ISSUE TITLE
xcopy script is failing on the error below.

### ISSUE THREAD

**Issue by jmakurami09** [stm32duino/Arduino_Core_STM8#30]
I'm running on Win 7, Arduino 1.8.16

When I compile a sketch, the final step throws the error below.

`Sketch uses 7488 bytes (5%) of program storage space. Maximum is 131072 bytes.
Global variables use 637 bytes (10%) of dynamic memory, leaving 5507 bytes for local variables. Maximum is 6144 bytes.
C:\Users\jmak\AppData\Local\Arduino15\packages\STMicroelectronics\tools\STM8Tools\1.0.0/win/massStorageCopy.bat -I C:\Users\jmak\AppData\Local\Temp\arduino_build_814597/sketch_sep21a.ino.bin -O NODE_8S208 
Does = specify a file name
or directory name on the target
(F = file, D = directory)? An error occurred while uploading the sketch
`

**Comment by fpistm** [comment]
Hi @jmakurami09 
Could you share the full log ?
The script is available here:
https://github.com/stm32duino/Arduino_Tools_STM8/blob/master/win/massStorageCopy.bat

**Comment by jmakurami09** [comment]
I updated my original issue.

I am using a ST Nucleo-8S208RB dev board

**Comment by jmakurami09** [comment]
> Hi @jmakurami09
> Could you share the full log ?
> The script is available here:
> https://github.com/stm32duino/Arduino_Tools_STM8/blob/master/win/massStorageCopy.bat

I have the script but the xcopy is failing, it appears to have an extra parameter that is not needed.

**Comment by jmakurami09** [comment]
Looks like this was related to the "wmic's module - logicaldisk" - so I hardcoded the Device ID in the script and voila.

**Comment by fpistm** [comment]
OK.
Maybe you have a device which cause some trouble with an "=".
I could not reproduce this the WMIC command is used since a while. This is the same command used for the STM32 core:
https://github.com/stm32duino/Arduino_Tools/blob/4bfe2102721da20ab2fa98126ea195cc52f54159/win/massStorageCopy.bat#L43-L48
which is largely used.

If you find a generic solution feel free to submit a PR then I will validate it on win 10.
